language: node_js

node_js:
  - "10"

sudo: required

services:
  - docker

deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESS_KEY"
  secret_access_key: "$SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "travisnode"
  env: "Travisnode-env"
  bucket_name: "elasticbeanstalk-us-east-2-517280624701"
